name: admin_kamus_sahu
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.10.0
  cloud_firestore: 4.5.3
  google_fonts: 4.0.3
  flutter_screenutil: 5.7.0
  lottie: 2.3.0
  flutter_svg: 2.0.4
  flutter_statusbarcolor_ns: 0.5.0
  eva_icons_flutter: 3.1.0
  file_picker: 5.2.6
  firebase_storage: 11.0.16
  connectivity_plus: 3.0.3
  shared_preferences: 2.0.20
  flutter_quill: 7.0.3
  just_audio: 0.9.32
  shimmer: 2.0.0
  flutter_easyloading: 3.0.5
  firebase_auth: 4.4.2
  awesome_dialog: 3.0.2
  fluttericon: 2.0.0
  rxdart: 0.27.7
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
  uses-material-design: true

